// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protobeans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TextMessage struct {
	Receiver int32  `protobuf:"varint,1,opt,name=receiver" json:"receiver,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	SendTime int64  `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
}

func (m *TextMessage) Reset()                    { *m = TextMessage{} }
func (m *TextMessage) String() string            { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()               {}
func (*TextMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *TextMessage) GetReceiver() int32 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *TextMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TextMessage) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type TextMessgeResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *TextMessgeResponse) Reset()                    { *m = TextMessgeResponse{} }
func (m *TextMessgeResponse) String() string            { return proto.CompactTextString(m) }
func (*TextMessgeResponse) ProtoMessage()               {}
func (*TextMessgeResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *TextMessgeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *TextMessgeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReceiveTextMessage struct {
	Sender   int32  `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	SendTime int64  `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
}

func (m *ReceiveTextMessage) Reset()                    { *m = ReceiveTextMessage{} }
func (m *ReceiveTextMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceiveTextMessage) ProtoMessage()               {}
func (*ReceiveTextMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ReceiveTextMessage) GetSender() int32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *ReceiveTextMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReceiveTextMessage) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func init() {
	proto.RegisterType((*TextMessage)(nil), "protobeans.TextMessage")
	proto.RegisterType((*TextMessgeResponse)(nil), "protobeans.TextMessgeResponse")
	proto.RegisterType((*ReceiveTextMessage)(nil), "protobeans.ReceiveTextMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xb1, 0x8b, 0x83, 0x30,
	0x14, 0xc6, 0x89, 0xa2, 0xe7, 0xbd, 0xe3, 0x6e, 0x08, 0x22, 0xe1, 0x26, 0x71, 0x72, 0x72, 0xe9,
	0xd6, 0xb1, 0x7b, 0x97, 0xe0, 0x5e, 0x62, 0xfa, 0x50, 0x11, 0x13, 0x49, 0x42, 0x29, 0xfe, 0xf5,
	0x45, 0xa3, 0xd2, 0xb9, 0xd3, 0xc7, 0x0f, 0x92, 0xef, 0xfb, 0xf1, 0xe0, 0x77, 0x44, 0x6b, 0x45,
	0x8b, 0xd5, 0x64, 0xb4, 0xd3, 0x14, 0xd6, 0x68, 0x50, 0x28, 0x5b, 0xdc, 0xe0, 0xa7, 0xc6, 0xa7,
	0xbb, 0xfa, 0x07, 0xf4, 0x1f, 0x12, 0x83, 0x12, 0xfb, 0x07, 0x1a, 0x46, 0x72, 0x52, 0x46, 0xfc,
	0x60, 0xca, 0xe0, 0x4b, 0x6a, 0xe5, 0x50, 0x39, 0x16, 0xe4, 0xa4, 0xfc, 0xe6, 0x3b, 0x2e, 0xbf,
	0x2c, 0xaa, 0x7b, 0xdd, 0x8f, 0xc8, 0xc2, 0x9c, 0x94, 0x21, 0x3f, 0xb8, 0x38, 0x03, 0xdd, 0x07,
	0x5a, 0xe4, 0x68, 0x27, 0xad, 0x2c, 0xd2, 0x3f, 0x08, 0xf4, 0xb0, 0x2e, 0x24, 0x3c, 0xd0, 0x03,
	0x4d, 0x21, 0x42, 0x63, 0xb4, 0xd9, 0x9a, 0x3d, 0x14, 0x0d, 0x50, 0xee, 0xd7, 0xdf, 0x1d, 0x33,
	0x88, 0x97, 0xf6, 0xc3, 0x70, 0xa3, 0xcf, 0xfc, 0x2e, 0x19, 0xa4, 0x23, 0x56, 0xfd, 0x3c, 0x4f,
	0x95, 0xec, 0x84, 0xec, 0x84, 0x3f, 0x52, 0x13, 0xaf, 0x71, 0x7a, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x5b, 0x5c, 0xe8, 0x3c, 0x01, 0x00, 0x00,
}
