// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protobeans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TextMessage struct {
	Receiver int32  `protobuf:"varint,1,opt,name=receiver" json:"receiver,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	SendTime int64  `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
}

func (m *TextMessage) Reset()                    { *m = TextMessage{} }
func (m *TextMessage) String() string            { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()               {}
func (*TextMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TextMessage) GetReceiver() int32 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *TextMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TextMessage) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type TextMessgeResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *TextMessgeResponse) Reset()                    { *m = TextMessgeResponse{} }
func (m *TextMessgeResponse) String() string            { return proto.CompactTextString(m) }
func (*TextMessgeResponse) ProtoMessage()               {}
func (*TextMessgeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *TextMessgeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *TextMessgeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReceiveTextMessage struct {
	Sender   int32  `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	SendTime int64  `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
}

func (m *ReceiveTextMessage) Reset()                    { *m = ReceiveTextMessage{} }
func (m *ReceiveTextMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceiveTextMessage) ProtoMessage()               {}
func (*ReceiveTextMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ReceiveTextMessage) GetSender() int32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *ReceiveTextMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReceiveTextMessage) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func init() {
	proto.RegisterType((*TextMessage)(nil), "protobeans.TextMessage")
	proto.RegisterType((*TextMessgeResponse)(nil), "protobeans.TextMessgeResponse")
	proto.RegisterType((*ReceiveTextMessage)(nil), "protobeans.ReceiveTextMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xbd, 0xaa, 0x83, 0x40,
	0x10, 0x85, 0x59, 0x45, 0xaf, 0x77, 0x42, 0x52, 0x2c, 0x21, 0x2c, 0xa9, 0xc4, 0xca, 0x2a, 0x4d,
	0xba, 0xbc, 0x43, 0x9a, 0xc5, 0x3e, 0xa8, 0x39, 0x88, 0x88, 0x3b, 0xb2, 0xbb, 0x84, 0x3c, 0x7e,
	0xf0, 0x97, 0xd4, 0xa9, 0x86, 0x0f, 0x66, 0xce, 0xf9, 0x18, 0xda, 0xf7, 0x70, 0xae, 0x6c, 0x70,
	0x19, 0x2c, 0x7b, 0x96, 0x34, 0x8d, 0x0a, 0xa5, 0x71, 0xd9, 0x83, 0x76, 0x05, 0xde, 0xfe, 0x3e,
	0x2f, 0xc8, 0x33, 0x25, 0x16, 0x35, 0xda, 0x17, 0xac, 0x12, 0xa9, 0xc8, 0x23, 0xbd, 0xb1, 0x54,
	0xf4, 0x57, 0xb3, 0xf1, 0x30, 0x5e, 0x05, 0xa9, 0xc8, 0xff, 0xf5, 0x8a, 0xe3, 0x95, 0x83, 0x79,
	0x16, 0x6d, 0x0f, 0x15, 0xa6, 0x22, 0x0f, 0xf5, 0xc6, 0xd9, 0x8d, 0xe4, 0x5a, 0xd0, 0x40, 0xc3,
	0x0d, 0x6c, 0x1c, 0xe4, 0x81, 0x02, 0xee, 0xa6, 0x86, 0x44, 0x07, 0xdc, 0xc9, 0x23, 0x45, 0xb0,
	0x96, 0xed, 0x92, 0x3c, 0x43, 0x56, 0x91, 0xd4, 0x73, 0xfb, 0xb7, 0xe3, 0x89, 0xe2, 0x31, 0x7d,
	0x33, 0x5c, 0xe8, 0x37, 0xbf, 0x2a, 0x9e, 0x9e, 0x71, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5a,
	0xd8, 0xcc, 0xc1, 0x24, 0x01, 0x00, 0x00,
}
